# Generated by Django 3.2 on 2021-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210425_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
